@startuml
'https://plantuml.com/deployment-diagram

title Diagrama de Despliegue Rueditas Amigas

actor "Admin"
actor "Usuario"

cloud "Internet"

node "Servidor"

database "Base de datos"

"Usuario" --> "Internet"
"Admin" --> "Internet"

"Internet" -l-> "Servidor"

"Servidor" -[bold]-> "Base de datos"

node "balanceador"
"Internet" -l-> "LoadBalancer"
"LoadBalancer" --> "Servidor"

@enduml
