@startuml
'https://plantuml.com/deployment-diagram

title Diagrama de Despliegue Rueditas Amigas

node "SistemaGeneradorDeRutas"
actor "Cliente"
cloud "Internet"
node "SistemaNotificacionProfesional"


rectangle  {
node "LoadBalancer"
node "Servidor1RueditasAmigas"
node "Servidor2RueditasAmigas"
database "BaseDeDatos"
}

"LoadBalancer" --> "Servidor1RueditasAmigas" : "JDBC"
"LoadBalancer" --> "Servidor2RueditasAmigas"
"Servidor1RueditasAmigas" --> "BaseDeDatos"
"Servidor2RueditasAmigas" --> "BaseDeDatos" : "HTTP"
"Servidor1RueditasAmigas" --> "SistemaNotificacionProfesional"
"Servidor2RueditasAmigas" --> "SistemaNotificacionProfesional"
"Servidor1RueditasAmigas" --> "SistemaGeneradorDeRutas"
"Servidor2RueditasAmigas" --> "SistemaGeneradorDeRutas"
"Cliente" --> "Internet"
"Internet" --> "LoadBalancer"


@enduml